title: ЧЕРВЕПЕДИЯ
description: Черветред - антироссиянский тред на Дваче
baseurl: "" # использовать /если/этот/сайт/вложен
url: ""

# Настройки permalink
permalink: /:categories/:year/:month/:day/:title/

# Настройка меню
menu:
  - title: Главная
    url: /
    icon: fa-home
  - title: Меню
    icon: fa-bars
    sub_menu:
      - title: Обр на Тучаннел
        url: http://www1.2channel.moe/pol
        target: _blank
      - title: Черветред
        url: /about
      - title: Контакты
        url: /contact
 

# Плагины
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-paginate
  - jekyll-loading-lazy

# Настройки пагинации
paginate: 10
paginate_path: "/page:num/"

# Конфигурация SEO Tag
seo:
  title: true
  description: true
  url: true
  image: true  # Добавлено для обработки Open Graph изображений
  twitter: true # Для Twitter Cards
